[tasks.fmt]
description = "Format project source code"
depends = ["*:*fmt"]

[tasks."fmt:check"]
description = "Check source formatting"
depends = ["*:fmt:check"]

[tasks."sort:crates"]
description = "Sort Cargo manifest dependencies"
run = "cargo sort --workspace --grouped --no-format --order package,dependencies,features"

[tasks."sort:crates:check"]
description = "Check Cargo manifest dependency ordering"
run = "cargo sort --workspace --grouped --order package,dependencies,features --check"

[tasks.lint]
description = "Run all lint checks"
depends = ["rust:lint:clippy"]

[tasks."lint:all-features"]
description = "Run all lint checks with all features"
depends = ["rust:lint:clippy:all-features"]

[tasks."deps:check"]
description = "Check dependency policy"
depends = ["rust:deps:check"]

[tasks.check]
description = "Check project source code"
depends = ["rust:check:workspace"]

[tasks."check:all-features"]
description = "Check project source code with all features"
depends = ["rust:check:all-features"]

[tasks.test]
description = "Run tests"
alias = "t"
depends = ["rust:test"]

[tasks."test:all-features"]
description = "Run tests with all features"
depends = ["rust:test:all-features"]

[tasks."pre-commit"]
description = "Run the full local development gate"
alias = "prk"
depends = [
  "sort:crates:check",
  "fmt:check",
  "lint",
  "deps:check",
  "check",
  "test",
]
