[package]
name = "slik"
version = { workspace = true }
description = "CLI for running GStreamer pipelines."
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
gstconsole = { workspace = true }
gstlines = { workspace = true }
gstreamer-video = { workspace = true }
gstsmith-app = { workspace = true }
ort = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tract-metal = { workspace = true, optional = true }
tract-onnx = { workspace = true }

[features]
default = []
coreml = ["ort/coreml"]
metal = ["dep:tract-metal"]

[lints]
workspace = true
